name: developer_resume
description: An example app to demonstrate that what I am developing a clean application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.0
  easy_localization: ^3.0.1
  url_launcher: ^6.1.3

dev_dependencies:
  effective_dart: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

   # YOU CAN GROUP YOUR ASSETS IN THIS FOLDERS
  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/projects/
    - assets/projects/sive/
    
   # THIS IS MY FAVORITE FONTS, ITs A GIFT FOR YOU 
  fonts:
      - family: SourseSansPro
        fonts:
          - asset: fonts/SourceSansPro-Light.ttf
          - asset: fonts/SourceSansPro-Regular.ttf